name: Flow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Flow
        run: npm install --save-dev flow-bin

      - name: Run Flow
        run: npx flow
